# Generated by Django 4.1.7 on 2026-01-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
    ]
